### ISSUE TITLE
CT:  invalid speed: NaN

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#139]
Seen once in CT:

```
gas-properties : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid magnitude: NaN
Error: Assertion failed: invalid magnitude: NaN
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/assert/js/assert.js:22:13)
    at LightParticle.setVelocityPolar (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/gas-properties/js/common/model/Particle.js?bust=1561611696932:152:17)
    at ParticleSystem.addParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/gas-properties/js/common/model/ParticleSystem.js?bust=1561611696932:270:18)
    at ParticleSystem.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/gas-properties/js/common/model/ParticleSystem.js?bust=1561611696932:215:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/gas-properties/js/common/model/ParticleSystem.js?bust=1561611696932:82:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/axon/js/TinyEmitter.js?bust=1561611696932:59:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/axon/js/Property.js?bust=1561611696932:247:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/axon/js/Property.js?bust=1561611696932:160:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/axon/js/NumberProperty.js?bust=1561611696932:87:13)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1561610154351/axon/js/Property.js?bust=1561611696932:316:34)
id: Bayes Chrome
Approximately 6/27/2019, 12:35:54 AM
```

**Comment by pixelzoom** [comment]
The relevant code is in `ParticleSystem`:

```js
        // Set the initial velocity
        particle.setVelocityPolar(
          // |v| = sqrt( 3kT / m )
          Math.sqrt( 3 * GasPropertiesConstants.BOLTZMANN * temperatures[ i ] / particle.mass ),

          // Velocity angle is randomly chosen from pump's dispersion angle, perpendicular to right wall of container.
          Math.PI - PARTICLE_DISPERSION_ANGLE / 2 + phet.joist.random.nextDouble() * PARTICLE_DISPERSION_ANGLE
        );
```

My guess is that `temperatures[ i ]` is (for some reason) invalid.  I'll add an assert to validate `temperatures` values where they are computed.

**Comment by pixelzoom** [comment]
This hasn't occurred again in CT, and I have not been able to manually reproduce it.  I'll leave this open for a bit longer.

**Comment by pixelzoom** [comment]
Appeared in CT for gases-intro, a derivative of gas-properties:

```
gases-intro : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas
Uncaught Error: Assertion failed: invalid magnitude: NaN
Error: Assertion failed: invalid magnitude: NaN
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/assert/js/assert.js:22:13)
    at LightParticle.setVelocityPolar (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/gas-properties/js/common/model/Particle.js?:153:17)
    at ParticleSystem.addParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/gas-properties/js/common/model/ParticleSystem.js?:271:18)
    at ParticleSystem.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/gas-properties/js/common/model/ParticleSystem.js?:215:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/gas-properties/js/common/model/ParticleSystem.js?:82:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/axon/js/TinyEmitter.js?:59:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/axon/js/Property.js?:247:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/axon/js/Property.js?:160:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/axon/js/NumberProperty.js?:90:13)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1563010429255/axon/js/Property.js?:316:34)
id: Bayes Chrome
Approximately 7/13/2019, 3:33:49 AM
```

**Comment by pixelzoom** [comment]
In the above commit, I added an assertion immediately following the speed computation in ParticleSystem `addParticles`:

```js
// Initial speed, |v| = sqrt( 3kT / m )
const speed = Math.sqrt( 3 * GasPropertiesConstants.BOLTZMANN * temperatures[ i ] / particle.mass );
assert && assert( typeof speed === 'number' && isFinite( speed ) && speed >= 0,
  `invalid speed: ${speed}, computed using temperature=${temperatures[ i ]}, mass=${particle.mass}` );
```

**Comment by pixelzoom** [comment]
This issue has only occurred a couple of times in CT, and I'm confident that it's a corner case.  So not a prerequisite to publishing 1.0.0, and deferred.

**Comment by pixelzoom** [comment]
Occurred in gases-intro on 8/6/19, and is hitting the assertion that was added in https://github.com/phetsims/gas-properties/issues/139#issuecomment-511902359.  It looks like temperature is negative, which should not occur.

````
gases-intro : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid speed: NaN, computed using temperature=-13.814382185731972, mass=28
Error: Assertion failed: invalid speed: NaN, computed using temperature=-13.814382185731972, mass=28
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at ParticleSystem.addParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/gas-properties/js/common/model/ParticleSystem.js?:288:19)
    at ParticleSystem.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/gas-properties/js/common/model/ParticleSystem.js?:231:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/gas-properties/js/common/model/ParticleSystem.js?:90:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/TinyEmitter.js?:59:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Property.js?:258:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Property.js?:170:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/NumberProperty.js?:90:13)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Property.js?:327:34)
    at HandleDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/BicyclePumpNode.js?:673:34)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
```

**Comment by pixelzoom** [comment]
In 872a05eddf3bec5a21225420749d505089ceef81, I added more detail to the assertion in `ParticleSystem.addParticles` (in master and 1.0 branches).

```js
        assert && assert( typeof speed === 'number' && isFinite( speed ) && speed >= 0,
          `invalid speed: ${speed}, computed using n=${n} meanTemperature=${meanTemperature} temperature=${temperatures[ i ]}, mass=${particle.mass}` );
```

**Comment by pixelzoom** [comment]
After hours of fuzz testing, I have not been able to reproduce this locally.

**Comment by pixelzoom** [comment]
gases-intro : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 8/29/2019, 8:38:16 PM
gases-intro : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid temperature: -8.295307909979158 n=28, meanTemperature=300, collisionsEnabled=true
Error: Assertion failed: invalid temperature: -8.295307909979158 n=28, meanTemperature=300, collisionsEnabled=true
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/assert/js/assert.js:22:13)
    at ParticleSystem.addParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/gas-properties/js/common/model/ParticleSystem.js?:281:17)
    at ParticleSystem.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/gas-properties/js/common/model/ParticleSystem.js?:231:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/gas-properties/js/common/model/ParticleSystem.js?:90:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/axon/js/TinyEmitter.js?:59:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/axon/js/Property.js?:258:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/axon/js/Property.js?:170:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/axon/js/NumberProperty.js?:90:13)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/axon/js/Property.js?:327:34)
    at HandleDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/snapshot-1567132696741/scenery-phet/js/BicyclePumpNode.js?:673:34)
id: Bayes Chrome
Approximately 8/29/2019, 8:38:16 PM

**Comment by KatieWoe** [comment]
Leaving open for https://github.com/phetsims/qa/issues/832 since it says this appears rarely on CT. But please close if appropriate @pixelzoom

**Comment by marlitas** [comment]
This error does not appear in the last 40 columns of CT and has not been worked on since 2019. It appears that this issue may be stale. Closing as such.
