### ISSUE TITLE
CT: invalid temperature: null

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#168]
```
gas-properties : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid temperature: null
Error: Assertion failed: invalid temperature: null
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/assert/js/assert.js:22:13)
    at ParticleSystem.setTemperature (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/gas-properties/js/common/model/ParticleSystem.js?:326:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/gas-properties/js/common/model/IdealGasLawModel.js?:220:31
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/TinyEmitter.js?:59:55)
    at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/Property.js?:258:27)
    at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/Property.js?:170:14)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/DerivedProperty.js?:65:19)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/TinyEmitter.js?:59:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/Property.js?:258:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1567084619993/axon/js/Property.js?:170:14)
id: Bayes Chrome
Approximately 8/29/2019, 7:16:59 AM
gas-properties : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 8/29/2019, 7:16:59 AM
```

**Comment by pixelzoom** [comment]
I'm going to defer work on this until 1.0.1 is published, since that RC process is close to wrapping up.

**Comment by KatieWoe** [comment]
```
gases-intro : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid temperature: null
Error: Assertion failed: invalid temperature: null
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/assert/js/assert.js?bust=1573615477031:22:13)
    at ParticleSystem.setTemperature (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/gas-properties/js/common/model/ParticleSystem.js?bust=1573615477102:327:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/gas-properties/js/common/model/IdealGasLawModel.js?bust=1573615477102:221:31
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/TinyEmitter.js?bust=1573615477102:68:55)
    at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/Property.js?bust=1573615477102:275:27)
    at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/Property.js?bust=1573615477102:176:16)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/DerivedProperty.js?bust=1573615477102:66:19)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/TinyEmitter.js?bust=1573615477102:68:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/Property.js?bust=1573615477102:275:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1573591283182/axon/js/Property.js?bust=1573615477102:176:16)
id: Bayes Chrome
Approximately 11/12/2019, 1:41:23 PM
gases-intro : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 11/12/2019, 1:41:23 PM
gases-intro : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 11/12/2019, 1:41:23 PM
```
Another example

**Comment by pixelzoom** [comment]
Both of the above examples are occurring in the same situation, in the same code. 

The assertion failure occurs in `setTemperature` at line 328 of `ParticleSystem`:

```js
    /**
     * Adjusts velocities of particle inside the container so that the resulting temperature matches
     * a specified temperature.
     * @param {number} temperature - in K
     * @public
     */
    setTemperature( temperature ) {
328   assert && assert( typeof temperature === 'number', `invalid temperature: ${temperature}` );
```
<br>

The call to `setTemperature` occurs at line 221 in `IdealGasLawModel`, while temperature is being held constant:

```js
      // When the number of particles (N) is decreased while holding temperature (T) constant, adjust the speed of
      // particles to result in the desired temperature.  We only need to do this when N decreases because particles
      // that are added have their initial speed set based on T of the container, and therefore result in no change
      // to T. See https://github.com/phetsims/gas-properties/issues/159
      this.particleSystem.numberOfParticlesProperty.link( ( numberOfParticles, previousNumberOfParticles ) => {
        if ( numberOfParticles > 0 && numberOfParticles < previousNumberOfParticles &&
             this.holdConstantProperty.value === HoldConstant.TEMPERATURE ) {
          assert && assert( !this.temperatureModel.controlTemperatureEnabledProperty.value,
            'this feature is not compatible with user-controlled particle temperature' );
          
221       this.particleSystem.setTemperature( this.temperatureModel.temperatureProperty.value );
        }
      } );
```

**Comment by pixelzoom** [comment]
Another data point:

```
gas-properties : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid temperature: -14.757586780047461n=50, meanTemperature=300, collisionsEnabled=true
Error: Assertion failed: invalid temperature: -14.757586780047461n=50, meanTemperature=300, collisionsEnabled=true
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/assert/js/assert.js?bust=1576550048833:22:13)
    at ParticleSystem.addParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/gas-properties/js/common/model/ParticleSystem.js?bust=1576550048924:282:17)
    at ParticleSystem.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/gas-properties/js/common/model/ParticleSystem.js?bust=1576550048924:232:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/gas-properties/js/common/model/ParticleSystem.js?bust=1576550048924:97:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/axon/js/TinyEmitter.js?bust=1576550048924:68:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/axon/js/Property.js?bust=1576550048924:275:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/axon/js/Property.js?bust=1576550048924:176:16)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/axon/js/NumberProperty.js?bust=1576550048924:134:13)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/axon/js/Property.js?bust=1576550048924:345:34)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1576543451267/scenery-phet/js/FineCoarseSpinner.js?bust=1576550048924:111:29
id: Bayes Chrome
Approximately 12/16/2019, 5:44:11 PM
```

**Comment by pixelzoom** [comment]
Still occurring -- not always, but consistently:

```
gas-properties : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/phet-io-wrappers/state/?sim=gas-properties&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1592651885106%22%2C%22timestamp%22%3A1592726930180%7D
Uncaught Error: Assertion failed: invalid temperature: null
Error: Assertion failed: invalid temperature: null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/assert/js/assert.js:22:13)
at ParticleSystem.setTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/gas-properties/js/common/model/ParticleSystem.js:333:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/gas-properties/js/common/model/IdealGasLawModel.js:218:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/Property.js:273:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/Property.js:323:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/PropertyStateHandler.js:263:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/PropertyStateHandler.js:197:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/PropertyStateHandler.js:71:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592651885106/axon/js/TinyEmitter.js:69:53)
id: Bayes Chrome
Snapshot from 6/20/2020, 5:18:05 AM
```

**Comment by pixelzoom** [comment]
Still occurring occasionally as of 8/27/2020.  I'd like to find time to investigate, so that CT is clear.

```
gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598529565763%22%2C%22timestamp%22%3A1598532802249%7D
Uncaught Error: Uncaught Error: Assertion failed: invalid temperature: null
Error: Assertion failed: invalid temperature: null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/assert/js/assert.js:22:13)
at ParticleSystem.setTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/gas-properties/js/common/model/ParticleSystem.js:333:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/gas-properties/js/common/model/IdealGasLawModel.js:218:29
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/Property.js:277:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/Property.js:175:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/DerivedProperty.js:73:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/TinyEmitter.js:71:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/Property.js:277:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598529565763/axon/js/Property.js:175:14)
id: Bayes Chrome
Snapshot from 8/27/2020, 5:59:25 AM
```

**Comment by pixelzoom** [comment]
Reported as a duplicate in https://github.com/phetsims/gases-intro/issues/8 on 11/6/2020.

**Comment by pixelzoom** [comment]
This still happens failure regularly, in all of the 3 sims in this family.  

The failure occurs when `setTemperature` is called in this listener:

```js
    this.particleSystem.numberOfParticlesProperty.link( ( numberOfParticles, previousNumberOfParticles ) => {
      if ( numberOfParticles > 0 && numberOfParticles < previousNumberOfParticles &&
           this.holdConstantProperty.value === HoldConstant.TEMPERATURE ) {
        assert && assert( !this.temperatureModel.controlTemperatureEnabledProperty.value,
          'this feature is not compatible with user-controlled particle temperature' );

        this.particleSystem.setTemperature( this.temperatureModel.temperatureProperty.value );
      }
    } );
```

My guess is that there's an ordering problem.  The temperature model probably also needs to update when this state occurs, but it's still null.   It could probably be addressed by adding this before the call to `setTemperature`:

```js
this.temperatureModel.update();
```

I'll give that a try.

**Comment by pixelzoom** [comment]
Workaround pushed.  I'll leave this open for a week, to see if it recurrs in CT.

**Comment by pixelzoom** [comment]
No sign of this in CT, so I'll go ahead and close.
