### ISSUE TITLE
CT: value failed isValidValue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#181]
Another CT failure related to the State wrapper, alternates with #178 and #182.  This stack trace is in gases-intro, but it also occurs in gas-properties.   It does not occur in diffusion.
```
gases-intro : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed isValidValue: 11726.672952586207
Error: Assertion failed: value failed isValidValue: 11726.672952586207
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/assert/js/assert.js?bust=1583870420489:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/axon/js/ValidatorDef.js:298:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/axon/js/validate.js:27:18)
    at NumberProperty.Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/axon/js/Property.js:138:32)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/axon/js/PropertyIO.js:116:16)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/axon/js/NumberPropertyIO.js:76:20)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583867545502/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
id: Bayes Chrome
Approximately 3/10/2020, 1:12:25 PM
```

**Comment by pixelzoom** [comment]
I asked the PhET-iO team how to identify which Property is failing. They recommended using "Pause on exception", or putting a `debugger` statement in assert.js.  Neither of those approaches works, I get the same call stack .  This is occurring when the sim is restoring state, setting a Property.   So there's no way to identify where that Property is defined.  Adding the phetioID to the assertion message seems essential.

**Comment by pixelzoom** [comment]
I guess we're not going to add the phetioID to the assertion message, because the assertion is in AXON/ValidatorDef, which shouldn't know anything about phetioID.

Inspecting the stack trace, I can find the phetioID:

NumberProperty.tandem.phetioID -> "gasProperties.idealScreen.model.container.lidWidthProperty"

**Comment by pixelzoom** [comment]
Fixing this issue will certainly result in some other issue with restoring state, because this sim does not yet have a coherent PhET-iO implementation. So this issue is deferred pending PhET-iO design in #30.

**Comment by pixelzoom** [comment]
Here's more current CT output, with URL:

```
gas-properties : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/phet-io-wrappers/state/?sim=gas-properties&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: value failed isValidValue: 13075
Error: Assertion failed: value failed isValidValue: 13075
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/axon/js/ValidatorDef.js:298:39)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/axon/js/validate.js:27:18)
    at NumberProperty.Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/axon/js/Property.js:138:32)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/axon/js/Property.js:167:29)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/axon/js/PropertyIO.js:116:16)
    at Function.setValue (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/axon/js/NumberPropertyIO.js:76:20)
    at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/phet-io/js/PhetioStateEngine.js:317:29)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586272767099/phet-io/js/PhetioStateEngine.js:262:14
    at Array.forEach (<anonymous>)
id: Bayes Chrome
Approximately 4/7/2020, 9:19:27 AM
```

**Comment by KatieWoe** [comment]
Not seeing this in CT right now. Closing. Feel free to reopen if in error.
