### ISSUE TITLE
CT: openingLeft 6880 must be <= openingRight -2000

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#192]
Very rare in CT, I've seen it happen once so far.

```
gas-properties : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/gas-properties/gas-properties_en.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612839790218%22%2C%22timestamp%22%3A1612866843204%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: openingLeft 6880 must be <= openingRight -2000
Error: Assertion failed: openingLeft 6880 must be <= openingRight -2000
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/assert/js/assert.js:25:13)
at IdealGasLawContainer.getOpeningLeft (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/gas-properties/js/common/model/IdealGasLawContainer.js:229:15)
at IdealGasLawContainer.getOpeningWidth (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/gas-properties/js/common/model/IdealGasLawContainer.js:251:56)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/gas-properties/js/common/model/IdealGasLawContainer.js:97:33
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/axon/js/DerivedProperty.js:101:34)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/axon/js/Property.js:289:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/axon/js/Property.js:187:14)
at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/axon/js/Property.js:359:32)
at buttonListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612839790218/gas-properties/js/common/view/ReturnLidButton.js:39:39)
id: Bayes Chrome
Snapshot from 2/8/2021, 8:03:10 PM
```

**Comment by KatieWoe** [comment]
Seen in intro:
```
gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631352162505%22%2C%22timestamp%22%3A1631408986956%7D
Uncaught Error: Uncaught Error: Assertion failed: openingLeft -143 must be <= openingRight -2000
Error: Assertion failed: openingLeft -143 must be <= openingRight -2000
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/assert/js/assert.js:25:13)
at IdealGasLawContainer.getOpeningLeft (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawContainer.js:229:15)
at IdealGasLawContainer.getOpeningWidth (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawContainer.js:251:56)
at IdealGasLawContainer.setWidth (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawContainer.js:170:33)
at IdealGasLawContainer.resizeImmediately (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawContainer.js:189:10)
at IdealModel.compensateForHoldConstant (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:400:22)
at IdealModel.updateModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:340:10)
at IdealModel.updateWhenPaused (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:360:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:137:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Multilink.js:47:11)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:22:42 AM

----------------------------------

gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631352162505%22%2C%22timestamp%22%3A1631489463773%7D
Uncaught Error: Uncaught Error: Assertion failed: empty container not supported
Error: Assertion failed: empty container not supported
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/assert/js/assert.js:25:13)
at IdealModel.computeIdealTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:476:15)
at IdealModel.compensateForHoldConstant (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:408:39)
at IdealModel.updateModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:340:10)
at IdealModel.updateWhenPaused (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:360:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:137:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Multilink.js:47:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:271:23)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:321:47)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:22:42 AM

----------------------------------

gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631352162505%22%2C%22timestamp%22%3A1631711946324%7D
Uncaught Error: Uncaught Error: Assertion failed: empty container not supported
Error: Assertion failed: empty container not supported
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/assert/js/assert.js:25:13)
at IdealModel.computeIdealTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:476:15)
at IdealModel.compensateForHoldConstant (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:408:39)
at IdealModel.updateModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:340:10)
at IdealModel.updateWhenPaused (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:360:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/IdealGasLawModel.js:137:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Multilink.js:47:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:271:23)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:321:47)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:22:42 AM

----------------------------------

gases-intro : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gases-intro/gases-intro_en.html?continuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1631352162505%22%2C%22timestamp%22%3A1631662756317%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid temperature: -30.158238342986863, n=50, meanTemperature=300, collisionsEnabled=true
Error: Assertion failed: invalid temperature: -30.158238342986863, n=50, meanTemperature=300, collisionsEnabled=true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/assert/js/assert.js:25:13)
at ParticleSystem.addParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/ParticleSystem.js:288:15)
at ParticleSystem.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/ParticleSystem.js:238:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/gas-properties/js/common/model/ParticleSystem.js:90:12
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:271:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:186:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:341:32)
at HandleDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/scenery-phet/js/BicyclePumpNode.js:707:32)
at HandleDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/scenery/js/listeners/PressListener.js:477:10)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:22:42 AM
```

**Comment by pixelzoom** [comment]
Looks like this is an older issue that I thought I had resolved.  Reopened https://github.com/phetsims/gas-properties/issues/108, closing this issue as duplicate.
