### ISSUE TITLE
CT model should not apply heat/cool in this mode

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#195]
```
gas-properties : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/gas-properties_en.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620275177198%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: model should not apply heat/cool in this mode
Error: Assertion failed: model should not apply heat/cool in this mode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/js/common/view/GasPropertiesHeaterCoolerNode.js:98:17
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:339:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/js/common/view/GasPropertiesHeaterCoolerNode.js:106:38
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM

----------------------------------

gas-properties : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/gas-properties_en.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620303931054%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: invalid temperature: null
Error: Assertion failed: invalid temperature: null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at ParticleSystem.setTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/js/common/model/ParticleSystem.js:333:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/js/common/model/IdealGasLawModel.js:218:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM

----------------------------------

gas-properties : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/gas-properties_en.html?continuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620280928463%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: model should not apply heat/cool in this mode
Error: Assertion failed: model should not apply heat/cool in this mode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/js/common/view/GasPropertiesHeaterCoolerNode.js:98:17
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:339:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/gas-properties/js/common/view/GasPropertiesHeaterCoolerNode.js:106:38
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM
```

**Comment by KatieWoe** [comment]
It looked fairly isolated, so my guess is it is a rare occurrence in CT.

**Comment by pixelzoom** [comment]
Based on the tests that are failing, this appears to involve multi-touch fuzzing.  I'm guessing that this happens if the "Hold Constant" mode is changed to `HoldConstant.PRESSURE_T` while the heater/cooler is being used.   Any change to `holdConstantProperty` should probably result in a call to `interruptSubtreeInput`, probably at the ScreenView level to be safe.

**Comment by pixelzoom** [comment]
It looks like `interruptSubtreeInput` is already handled for the heater/cooler. 
In GasPropertiesHeaterCoolerNode.js:

```js
    // When the Hold Constant mode changes...
    holdConstantProperty.link( holdConstant => {

      // cancel interaction
      this.interruptSubtreeInput();
```

**Comment by pixelzoom** [comment]
No problem in CT for 5 cycles.  And this assertion can't fail because it no longer exists.  So closing.
