### ISSUE TITLE
CT: empty container not supported

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#196]
This occurred once in CT for gases-intro, so probably just a rare corner case.  Creating the GitHub issues in gas-properties because gases-intro is a subset of gas-properties.

```
gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628175374123%22%2C%22timestamp%22%3A1628177986503%7D
Uncaught Error: Uncaught Error: Assertion failed: empty container not supported
Error: Assertion failed: empty container not supported
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/assert/js/assert.js:25:13)
at IdealModel.computeIdealTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/gas-properties/js/common/model/IdealGasLawModel.js:476:15)
at IdealModel.compensateForHoldConstant (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/gas-properties/js/common/model/IdealGasLawModel.js:408:39)
at IdealModel.updateModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/gas-properties/js/common/model/IdealGasLawModel.js:340:10)
at IdealModel.updateWhenPaused (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/gas-properties/js/common/model/IdealGasLawModel.js:360:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/gas-properties/js/common/model/IdealGasLawModel.js:137:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/axon/js/Multilink.js:47:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/axon/js/Property.js:271:23)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628175374123/axon/js/Property.js:321:47)
id: Bayes Chrome
Snapshot from 8/5/2021, 8:56:14 AM
```

**Comment by KatieWoe** [comment]
Can you confirm if this issue is still needed? I don't see it in CT right now, but it is noted as rare. For https://github.com/phetsims/qa/issues/832

**Comment by pixelzoom** [comment]
Yes, please keep this open.

**Comment by pixelzoom** [comment]
I haven't seen this occur in over a year.  While I suspect it's still a corner-case issue, I'll close.
