### ISSUE TITLE
CT: bad holdConstant state

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#239]
In gas-properties and gases-intro, because it's related to the "Hold Constant" feature:

```
gas-properties : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/phet-io-wrappers/state/?sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715298707649%22%2C%22timestamp%22%3A1715299676719%7D
Assertion failed: bad holdConstant state: temperature with numberOfParticles=0
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/assert/js/assert.js:28:13)
at assert (IdealGasLawModel.ts:282:16)
at (TinyEmitter.ts:213:16)
at notifyLoop (TinyEmitter.ts:185:17)
at emit (ReadOnlyProperty.ts:352:22)
at _notifyListeners (ReadOnlyProperty.ts:400:46)
at listener (PropertyStateHandler.ts:278:40)
at attemptToApplyPhases (PropertyStateHandler.ts:198:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:91:11)
at (TinyEmitter.ts:213:16)
at notifyLoop (TinyEmitter.ts:196:13)
at emit (Emitter.ts:64:21)
at emit (PhetioStateEngine.ts:263:24)
at setState (PhetioStateEngine.ts:280:9)
at setFullState (phetioEngine.ts:1158:33)
at apply (phetioCommandProcessor.ts:429:50)
at process (phetioCommandProcessor.ts:303:35)
at getReturn (phetioCommandProcessor.ts:311:17)
at map (phetioCommandProcessor.ts:301:29)
at processCommands (phetioCommandProcessor.ts:242:34)
at addEventListener (phetioCommandProcessor.ts:197:11)
at (phetioCommandProcessor.ts:545:31)
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1715298707649%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgas-properties%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715298707649%22%2C%22timestamp%22%3A1715299676719%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1715298707649%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgas-properties%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715298707649%22%2C%22timestamp%22%3A1715299676719%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/phet-io-wrappers/state/?sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715298707649%22%2C%22timestamp%22%3A1715299676719%7D
[ATTACHED]
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715298707649%22%2C%22timestamp%22%3A1715299676719%7D&frameTitle=source
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/gas-properties/gas-properties_en.html?brand=phet-io&ea&postMessageOnError&sim=gas-properties&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22gas-properties%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1715298707649%22%2C%22timestamp%22%3A1715299676719%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1715298707649/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: bad holdConstant state: temperature with numberOfParticles=0
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[PAGE ERROR] Error: Assertion failed: bad holdConstant state: temperature with numberOfParticles=0

id: "Sparky Node Firefox"
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/gas-properties/commit/9a90d366ed47d065de56cfe9e5c3b6bce0b5d4aa, I added a test for `isSettingPhetioStateProperty` that should fixed this.  And in that same commit, I added a few other such tests iwhere they seemed appropriate.  I'll leave this open to see if CT agrees.

**Comment by pixelzoom** [comment]
CT is happy, closing.
