### ISSUE TITLE
make Java version runnable in IntelliJ

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#34]
The legacy (Java) version of Gas Properties lives in Unfuddle SVN.   As of this writing, it fails to build or run.  I'm only planning to port the model from Java, but doing so will be much easier if I can run and inspect the Java version.   So I'm going to spend some time trying to sort this out. 

@arouinfar @ariel-phet FYI.

**Comment by pixelzoom** [comment]
First up is install IntellJ and the latest legacy codebase.

I installed IntelliJ CE 2018.2.6 (latest).  

I updated my SVN working copy and confirmed that it's revision number matches the latest 

```
% svn update
At revision 74946.
```

![unfuddle](https://user-images.githubusercontent.com/3046552/48507066-2270cb80-e808-11e8-8fc3-18bfa41f1a12.jpg)

**Comment by pixelzoom** [comment]
With the above Run Configuration, I see these errors: in `SWTGraphics2D`:

```
Error:(69, 32) java: cannot find symbol
  symbol:   class Path
  location: package org.eclipse.swt.graphics
Error:(70, 32) java: cannot find symbol
  symbol:   class Transform
  location: package org.eclipse.swt.graphics
```

The errors correspond to these lines in Piccolo's `SWTGraphics2D`:

```java
69 import org.eclipse.swt.graphics.Path;
79 import org.eclipse.swt.graphics.Transform;
```

`org.eclipse.swt` packages come from `simulations-java/common/contrib/swt/swt.jar`.  Expanding swt.jar in the Project window, I see that `Path` and `Transform` are missing from the jar:

![screenshot_865](https://user-images.githubusercontent.com/3046552/48507416-205b3c80-e809-11e8-8c38-256d2013d6e9.png)

**Comment by pixelzoom** [comment]
@samreid reported on Slack:

I’m set up to build and run ideal-gas in Java, but running into this problem:

```
Caused by: java.lang.NullPointerException
    at edu.colorado.phet.common.phetgraphics.view.phetgraphics.PhetMultiLineTextGraphic.<init>(PhetMultiLineTextGraphic.java:45)
    at edu.colorado.phet.common.phetgraphics.view.phetgraphics.PhetMultiLineTextGraphic.<init>(PhetMultiLineTextGraphic.java:34)
    at edu.colorado.phet.idealgas.view.WiggleMeGraphic.<init>(WiggleMeGraphic.java:35)
    at edu.colorado.phet.idealgas.GasPropertiesApplication.<init>(GasPropertiesApplication.java:36)
    at edu.colorado.phet.idealgas.GasPropertiesApplication$2.getApplication(GasPropertiesApplication.java:73)
    at edu.colorado.phet.common.phetcommon.application.PhetApplicationLauncher$1.run(PhetApplicationLauncher.java:122)
```

The above is a runtime error.  So this tells me that @samreid is able to actually run the sim (yeah!), but that I'll likely encounter this error when I get the sim to run (boo).

**Comment by pixelzoom** [comment]
PhETBuildGUI builds and runs.  But if I attempt to run `GasPropertiesApplication` (or any other sim), I hit these errors:

> JavaBuildCommand> Compiling java version checker for ideal-gas.
warning: [options] bootstrap class path not set in conjunction with -source 1.4
error: Source option 1.4 is no longer supported. Use 1.6 or later.
error: Target option 1.4 is no longer supported. Use 1.6 or later.
Errors on build

Probably related to this in BuildToolsConstants.java:

```js
15 public static final String BOOTSTRAP_JAVA_VERSION = "1.4"; // see java
```

**Comment by pixelzoom** [comment]
Thanks @samreid! That did the trick.  Rather than delete the directories, I excluded them (recursively) from compilation, see Preferences dialog below.   Gas Properties builds and runs, so closing this issue.

![screenshot_875](https://user-images.githubusercontent.com/3046552/48652767-7c1af680-e9be-11e8-926a-40fd872f09f3.png)

**Comment by samreid** [comment]
Just a thought--should we delete those swt directories from svn?  Our simulations do not use SWT at all.  We can recover the history if we ever need it.  And in the future we will not need to remember to exclude them before we can build.  I'm happy either way--just wanted to know your thoughts on the matter.

**Comment by pixelzoom** [comment]
Once you discovered this fix, I had a very faint recollection that we had encountered this problem before.  And when we were actively doing Java development and updating contrib/ packages, it made sense not to customize them (by changing code, deleting parts of the package, etc.) unless absolutely necessary.  But since we're unlikely to ever upgrade contrib/piccolo2D/, it's probably safe to delete the swt/ and swt-examples/ subdirectories.  Recommended to include a very clear commit message that references this issue.

**Comment by pixelzoom** [comment]
Here's the ticket that I was thinking of, from 10 (!) years ago.  Not IntelliJ + Piccolo2D, but the same problem with Eclipse + JMonkeyEngine. 
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/1666

**Comment by samreid** [comment]
I deleted those two directories and committed.  Here is my paper trail:

```
~/phet-svn-trunk-2/trunk$ svn delete simulations-java/contrib/piccolo2d/swt
D         simulations-java/contrib/piccolo2d/swt
D         simulations-java/contrib/piccolo2d/swt/pom.xml
D         simulations-java/contrib/piccolo2d/swt/src
D         simulations-java/contrib/piccolo2d/swt/src/build
D         simulations-java/contrib/piccolo2d/swt/src/build/conf
D         simulations-java/contrib/piccolo2d/swt/src/build/conf/checkstyle.xml
D         simulations-java/contrib/piccolo2d/swt/src/main
D         simulations-java/contrib/piccolo2d/swt/src/main/java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTBoundsHandle.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTCanvas.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTHandle.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTImage.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTKeyEvent.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTMouseEvent.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTPath.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTRoot.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTSelectionEventHandler.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTStickyHandleManager.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/PSWTText.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/SWTGraphics2D.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/SWTShapeManager.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/SWTTimer.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/SWTTimerQueue.java
D         simulations-java/contrib/piccolo2d/swt/src/main/java/edu/umd/cs/piccolox/swt/package.html
D         simulations-java/contrib/piccolo2d/swt/src/main/java/overview.html
D         simulations-java/contrib/piccolo2d/swt/src/test
D         simulations-java/contrib/piccolo2d/swt/src/test/java
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt/PSWTBoundsHandleTest.java
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt/PSWTCanvasTest.java
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt/PSWTHandleTest.java
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt/PSWTImageTest.java
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt/PSWTPathTest.java
D         simulations-java/contrib/piccolo2d/swt/src/test/java/edu/umd/cs/piccolox/swt/PSWTTextTest.java
~/phet-svn-trunk-2/trunk$ svn delete simulations-java/contrib/piccolo2d/swt-examples/src
D         simulations-java/contrib/piccolo2d/swt-examples/src
D         simulations-java/contrib/piccolo2d/swt-examples/src/main
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox/swt
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox/swt/examples
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox/swt/examples/SWTBasicExample.java
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox/swt/examples/SWTBenchTest.java
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox/swt/examples/SWTHelloWorld.java
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/java/edu/umd/cs/piccolox/swt/examples/package-info.java
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs/piccolox
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs/piccolox/swt
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs/piccolox/swt/examples
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs/piccolox/swt/examples/bitmask.gif
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs/piccolox/swt/examples/opaque.jpg
D         simulations-java/contrib/piccolo2d/swt-examples/src/main/resources/edu/umd/cs/piccolox/swt/examples/translucent.png
~/phet-svn-trunk-2/trunk$ svn commit -m "Remove swt and swt-examples to simplify builds, see https://github.com/phetsims/gas-properties/issues/34"
Deleting       simulations-java/contrib/piccolo2d/swt
Deleting       simulations-java/contrib/piccolo2d/swt-examples/src
Committing transaction...
Committed revision 74947.
```

**Comment by pixelzoom** [comment]
Reopening.  

@samreid in the above comment, you reported that you deleted both `piccolo2d/swt` and ``piccolo2d/swt-examples`.   But I still see `piccolo2d/swt-examples` in Unfuddle SVN, see screenshot below.   This is causing build problems for a 3rd party who contacted my directly, which prompted me to poke around.

Do you want to take another stab at deleting `piccolo2d/swt-examples`?

<img width="929" alt="screenshot_1265" src="https://user-images.githubusercontent.com/3046552/60547489-16754380-9cdd-11e9-8b0c-657e4dd037f9.png">

**Comment by pixelzoom** [comment]
Ah...  I see that you actually deleted `piccolo2d/swt` and `piccolo2d/swt-examples/src`.   Any reason why you treated them differently?

**Comment by samreid** [comment]
I don't recall why I treated them differently.  I suspect it would be safe to delete `piccolo2d/swt-examples` as it now only contains a pom.xml file.  I tested this hypothesis by deleting `swt-examples` locally and testing that gas-properties still ran in the IDE.  So I'll go ahead and commit this deletion.  Here is the paper trail:

```
~/phet-svn-trunk-2/trunk$ svn delete simulations-java/contrib/piccolo2d/swt-examples
D         simulations-java/contrib/piccolo2d/swt-examples
D         simulations-java/contrib/piccolo2d/swt-examples/pom.xml
~/phet-svn-trunk-2/trunk$ svn commit -m "remove swt-examples directory, see https://github.com/phetsims/gas-properties/issues/34"
Sending        simulations-java/contrib/piccolo2d/piccolo2d.iml
Deleting       simulations-java/contrib/piccolo2d/swt-examples
Transmitting file data .done
Committing transaction...
Committed revision 75011.
```

But I'm curious how the existence of swt-examples/pom.xml is causing problems for the client?  And what are the exact problems?

**Comment by pixelzoom** [comment]
👍 thanks, closing.

**Comment by pixelzoom** [comment]
Sorry, just saw this question:
> But I'm curious how the existence of swt-examples/pom.xml is causing problems for the client? And what are the exact problems?

It turned out that his problem  is not related to this, but it sent us on a wild-goose chase.
