### ISSUE TITLE
CT value failed isValidValue: 0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#76]
```
gas-properties : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 0
Error: Assertion failed: value failed isValidValue: 0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/ValidatorDef.js?bust=1557998511797:224:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/validate.js?bust=1557998511797:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557998511797:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557998511797:152:29)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557998511797:316:34)
    at IdealModel.stepPressure (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1557998511797:427:40)
    at IdealModel.stepModelTime (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1557998511797:254:40)
    at IdealModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/BaseModel.js?bust=1557998511797:103:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/joist/js/Sim.js?bust=1557998511797:220:22
id: Bayes Chrome
Approximately 5/15/2019, 11:20:50 PM
gas-properties : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 0
Error: Assertion failed: value failed isValidValue: 0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/ValidatorDef.js?bust=1558007087753:224:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/validate.js?bust=1558007087753:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1558007087753:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1558007087753:152:29)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1558007087753:316:34)
    at IdealModel.stepPressure (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1558007087753:427:40)
    at IdealModel.stepModelTime (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1558007087753:254:40)
    at IdealModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/BaseModel.js?bust=1558007087753:103:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/joist/js/Sim.js?bust=1558007087753:220:22
id: Bayes Chrome
Approximately 5/15/2019, 11:20:50 PM
gas-properties : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 0
Error: Assertion failed: value failed isValidValue: 0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/ValidatorDef.js?bust=1557989521682:224:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/validate.js?bust=1557989521682:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557989521682:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557989521682:152:29)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557989521682:316:34)
    at IdealModel.stepPressure (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1557989521682:427:40)
    at IdealModel.stepModelTime (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1557989521682:254:40)
    at IdealModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/BaseModel.js?bust=1557989521682:103:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/joist/js/Sim.js?bust=1557989521682:220:22
id: Bayes Chrome
Approximately 5/15/2019, 11:20:50 PM
gas-properties : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: mean: 3866621.1407366823, actualMean: 3866621.140736682
Error: Assertion failed: mean: 3866621.1407366823, actualMean: 3866621.140736682
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/assert/js/assert.js:22:13)
    at Object.getGaussianValues (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/GasPropertiesUtils.js?bust=1558015759882:50:17)
    at ExploreModel.addParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1558015759882:320:43)
    at ExploreModel.updateNumberOfParticles (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1558015759882:276:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1558015759882:89:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/TinyEmitter.js?bust=1558015759882:58:55)
    at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1558015759882:247:27)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1558015759882:160:14)
    at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/NumberProperty.js?bust=1558015759882:87:13)
    at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1558015759882:316:34)
id: Bayes Chrome
Approximately 5/15/2019, 11:20:50 PM
gas-properties : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: 0
Error: Assertion failed: value failed isValidValue: 0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/assert/js/assert.js:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/ValidatorDef.js?bust=1557990197529:224:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/validate.js?bust=1557990197529:28:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557990197529:84:44)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557990197529:152:29)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/axon/js/Property.js?bust=1557990197529:316:34)
    at IdealModel.stepPressure (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1557990197529:427:40)
    at IdealModel.stepModelTime (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/GasPropertiesModel.js?bust=1557990197529:254:40)
    at IdealModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/gas-properties/js/common/model/BaseModel.js?bust=1557990197529:103:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557984050677/joist/js/Sim.js?bust=1557990197529:220:22
id: Bayes Chrome
Approximately 5/15/2019, 11:20:50 PM
```

**Comment by pixelzoom** [comment]
The problem is in GasPropertiesModel:

```js
426  const pressure = this.pressureProperty.value / PRESSURE_CONVERSION_SCALE;
427  this.temperatureProperty.value = ( pressure * this.container.volume ) /
428                                   ( this.numberOfParticles * GasPropertiesConstants.BOLTZMANN );
```

`temperatureProperty` can never be zero; if there are no particles in the the container, then temperature is `null`.   But the real issue is that pressure should not be zero at this point.

**Comment by pixelzoom** [comment]
Fixed in the commit above.  I'll leave this issue open until it passes a couple of CT cycles.

**Comment by pixelzoom** [comment]
Looking good in CT, closing.
